### ISSUE TITLE
Essential Search result fixed width.

### ISSUE THREAD

**Issue by shubhamjain2998** [covid19india/covid19india.github.io#1195]
**Describe the bug**
Searching for different cities on the essentials page in mobile is resulting into list of different widths.

**To Reproduce**

1. Open the essential page on mobile.
2. Search for any city except Chandigarh and Jharkhand.
3. Notice the width of the list.

**Expected behavior**
A clean fixed-size list for every query should be there, with little padding between them and also bullets or serial numbers.

**Screenshots**
See the following ScreenShots

![image 3](https://user-images.githubusercontent.com/30628775/79495679-9721e800-8042-11ea-8f71-7558285688f3.jpeg)
![image 2](https://user-images.githubusercontent.com/30628775/79495684-98531500-8042-11ea-9afd-25dbfca02447.jpeg)
![image 1](https://user-images.githubusercontent.com/30628775/79495685-98ebab80-8042-11ea-9dad-83afbb890c42.jpeg)

**Smartphone (please complete the following information):**

- Device: [Redmi 4]
- OS: [Android 9]
- Browser [Chrome]
- Version [81.0]

**Additional context**
If this issue feels relevant, assign it to me, I can solve this issue.

**Comment by nikita-11** [comment]
This is fixed. Looks good now.

**Comment by shubhamjain2998** [comment]
@nikita-11 it is not yet fixed on the main website, see a preview, you can see the overlapping clearly (**Maybe** this issue still persist on small screen devices like phones with less than 5inch of the screen).
![notfixedd](https://user-images.githubusercontent.com/30628775/79690188-bef99180-8276-11ea-808e-d6b62e261bee.gif)

**Comment by shubhamjain2998** [comment]
hey @nikita-11, this bug is still showing, see the preview

![notfixedd](https://user-images.githubusercontent.com/30628775/79690796-e7cf5600-8279-11ea-9027-ec2059d70cf0.gif)
